services:  
  - type: web  
    name: workspaces-backend  
    env: docker  
    dockerfilePath: ./backend/Dockerfile  
    envVars:  
      - key: MONGO_COMMON_URI  
        sync: false  
      - key: MONGO_BASE_URI  
        sync: false  
      - key: JWT_SECRET  
        generateValue: true  
      - key: NODE_ENV  
        value: production  
    plan: free  
  
  - type: web  
    name: workspaces-frontend  
    env: docker  
    dockerfilePath: ./frontend/Dockerfile  
    envVars:  
      - key: VITE_API_URL  
        value: https://workspaces-backend.onrender.com  
    plan: free
